FROM ubuntu:groovy
ARG DEBIAN_FRONTEND="noninteractive"
ARG TARGETARCH
ARG CARDANO_VERSION=1.25.1
ARG JOBS="-j1"

COPY repo/cardano-${TARGETARCH}-${CARDANO_VERSION}.tgz /cardano.tgz
RUN apt-get -y update && apt-get -y upgrade && apt-get -y install --no-install-recommends bash curl jq miniupnpc iproute2 wget ca-certificates bc tcptraceroute netbase
RUN cd / && tar -xvzf /cardano.tgz && rm /cardano.tgz
RUN adduser --disabled-password --gecos "cardano" --uid 1001 cardano
COPY scripts/ /scripts/

#Runtime variables to init.sh
ENV LD_LIBRARY_PATH=/usr/local/lib \
  NODE_NETWORK="mainnet" \
  NODE_IP="" \
  NODE_LISTEN="0.0.0.0" \
  NODE_PORT="6000" \
  NODE_UPNP=false \
  NODE_RUNAS_CORE=false \
  NODE_UPDATE_TOPOLOGY=true \
  NODE_CUSTOM_PEERS="" \
  NODE_HOME="/home/cardano/cnode" \
  NODE_CONFIG="$NODE_HOME/config/mainnet-config.json" \
  NODE_TOPOLOGY="$NODE_HOME/config/mainnet-topology.json" \
  NODE_SHELLEY_KES_KEY="$NODE_HOME/keys/pool/kes.skey" \
  NODE_SHELLEY_VRF_KEY="$NODE_HOME/keys/pool/vrf.skey" \
  NODE_SHELLEY_OPERATIONAL_CERTIFICATE="$NODE_HOME/keys/pool/node.cert" \
  NODE_SCRIPTS=false
USER cardano

COPY init.sh /
STOPSIGNAL SIGINT
ENTRYPOINT [ "/init.sh" ]

