FROM ubuntu:groovy
ARG DEBIAN_FRONTEND="noninteractive"
ARG TARGETARCH
ARG CARDANO_VERSION=1.26.1
ARG JOBS="-j1"

COPY repo/cardano-${TARGETARCH}-${CARDANO_VERSION}.tgz /cardano.tgz
RUN apt-get -y update && apt-get -y upgrade && apt-get -y install --no-install-recommends bash curl jq miniupnpc iproute2 wget ca-certificates bc tcptraceroute netbase libnuma1
RUN cd / && tar -xvzf /cardano.tgz && rm /cardano.tgz
RUN adduser --disabled-password --gecos "cardano" --uid 1001 cardano
COPY scripts/ /scripts/

#Runtime variables to init.sh
ENV LD_LIBRARY_PATH=/usr/local/lib \
  NODE_NETWORK="mainnet" \
  NODE_IP="" \
  NODE_LISTEN="0.0.0.0" \
  NODE_PORT="6000" \
  NODE_UPNP=false \
  NODE_RUNAS_CORE=false \
  NODE_HOME="/home/cardano/cnode" \
  NODE_CONFIG="/home/cardano/cnode/config/mainnet-config.json" \
  NODE_TOPOLOGY="/home/cardano/cnode/config/mainnet-topology.json" \
  NODE_SHELLEY_KES_KEY="/home/cardano/cnode/keys/pool/kes.skey" \
  NODE_SHELLEY_VRF_KEY="/home/cardano/cnode/keys/pool/vrf.skey" \
  NODE_SHELLEY_OPERATIONAL_CERTIFICATE="/home/cardano/cnode/keys/pool/node.cert" \
  NODE_SCRIPTS=false \
  NODE_CUSTOM_PEERS="" \
  NODE_UPDATE_TOPOLOGY=true \
  NODE_TOPOLOGY_PUSH=false \
  NODE_TOPOLOGY_PULL=false \
  NODE_TOPOLOGY_PULL_MAX=10 \
  NODE_TRACE_FETCH_DECISIONS=true \
  NODE_TRACE_MEMPOOL=false \
  NODE_PROM_LISTEN="" 

HEALTHCHECK --interval=10m --timeout=3m --retries=3 --start-period=20m CMD /scripts/healthCheck.sh 180 || bash -c 'kill -s 2 -1 && (sleep 60; kill -s 9 -1)'

USER cardano

COPY init.sh /
STOPSIGNAL SIGINT
ENTRYPOINT [ "/init.sh" ]

